# Data Scaling or Transformation

---
# 1. Data Standardization
`Data Standardization`  ek technique hai jisse hum data ko ek standard scale pe la sakte hain. or 
data ko standard scale pe laane ka matlab hai ki data ka mean 0 or standard deviation 1 ho jaye.
Data standardization ka formula hai:
$$ z = (x- \mu) / \sigma $$

In [6]:
# import libraries

import pandas as pd
from sklearn.preprocessing import StandardScaler


data ={
    "age":[10,15,20,25,30,35,40,45,50,55],
   "height":[70,75,80,85,90,95,100,105,110,115],
   "weight":[30,35,40,45,50,55,60,65,70,75]

}


df=pd.DataFrame(data)

scaler=StandardScaler()

standardizing_data=scaler.fit_transform(df)
standardized_data=pd.DataFrame(standardizing_data,columns=["age","height","weight"])

standardized_data

        age    height    weight
0 -1.566699 -1.566699 -1.566699
1 -1.218544 -1.218544 -1.218544
2 -0.870388 -0.870388 -0.870388
3 -0.522233 -0.522233 -0.522233
4 -0.174078 -0.174078 -0.174078
5  0.174078  0.174078  0.174078
6  0.522233  0.522233  0.522233
7  0.870388  0.870388  0.870388
8  1.218544  1.218544  1.218544
9  1.566699  1.566699  1.566699

---
# Min-Max Scaler

`Min-Max Scaler` ek technique hai jisse hum data ko 0 se 1 ke beech me scale kar sakte hain.

In [8]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler,MaxAbsScaler

data={
    "Age":[1,2,3,4],
    "height":[5,6,7,8]
}

df=pd.DataFrame(data)

MinScaler=MinMaxScaler()
Minmax_scaling=MinScaler.fit_transform(df)
Minmax_scaled_data=pd.DataFrame(Minmax_scaling,columns=["Age","height"])

Minmax_scaled_data.head()

        Age    height
0  0.000000  0.000000
1  0.333333  0.333333
2  0.666667  0.666667
3  1.000000  1.000000

# Max Absolute Scaler

`Max Absolute Scaler` ek technique hai jisse hum data ko -1 se 1 ke beech me scale kar sakte hain.

In [11]:
import pandas as pd
from sklearn.preprocessing import MaxAbsScaler

data={
    "Age":[12,13,15],
    "height":[5,4,7]

}

df=pd.DataFrame(data)

Scaler=MaxAbsScaler()

MaxAbsScaling=Scaler.fit_transform(df)

MaxAbsScaled_data=pd.DataFrame(MaxAbsScaling,columns=["Age","height"])
MaxAbsScaled_data

        Age    height
0  0.800000  0.714286
1  0.866667  0.571429
2  1.000000  1.000000

# Robust Scaler

`Robust Scaler` ek technique hai jisse hum data ko outliers ke effect se bacha sakte hain. Robust Scaler data ko median or IQR se scale karta hai.

In [12]:
# import libraries

import pandas as pd
from sklearn.preprocessing import RobustScaler


data ={
    "age":[10,15,20,25,30,35,40,45,50,55],
   "height":[70,75,80,85,90,95,100,105,110,115],
   "weight":[30,35,40,45,50,55,60,65,70,75]

}


df=pd.DataFrame(data)

scaler=RobustScaler()

RobustScaling_data=scaler.fit_transform(df)
RobustScaled_data=pd.DataFrame(standardizing_data,columns=df.columns)

RobustScaled_data

        age    height    weight
0 -1.566699 -1.566699 -1.566699
1 -1.218544 -1.218544 -1.218544
2 -0.870388 -0.870388 -0.870388
3 -0.522233 -0.522233 -0.522233
4 -0.174078 -0.174078 -0.174078
5  0.174078  0.174078  0.174078
6  0.522233  0.522233  0.522233
7  0.870388  0.870388  0.870388
8  1.218544  1.218544  1.218544
9  1.566699  1.566699  1.566699

# 2. Data Normalization

In [ ]:
# https://scikit-learn.org/stable/modules/preprocessing.html  go to this link for detailed concepts